export const CHEAT = '/cheat'
export const BASE_WOW_API_URL = 'https://wow-crescer-api.herokuapp.com'
export const RACES_URL = '/races'
export const SHOP_ITEMS_URL = '/shop'
export const LOGIN_URL = '/auth/login'
export const USER_CHARACTERS_URL = '/user/me/characters'
export const CREATE_CHARACTER_URL = '/user/create-character'
export const REGISTER_URL = '/auth/register'
export const QUEST_URL = '/quests'
export const USER_URL = '/user/me'
export const BATTLE_URL = '/battle'
export const CHARACTERS_URL = '/characters'

export const LOGIN_ROUTE = '/'
export const VOTE_ROUTE = '/voting'
export const QUEST_FINISH_URL = '/quests/finish'